//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anbarii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Load()
        {
            this.ReceiptDetails = new HashSet<ReceiptDetail>();
            this.RowDetailsD = new HashSet<RowDetail>();
            this.RowDetailsS = new HashSet<RowDetail>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public int Count { get; set; }
        public double Weight { get; set; }
        public string Weight_Type { get; set; }
        public int Load_TypeID { get; set; }
        public int Inventory_price { get; set; }
        public int Packaging_Price { get; set; }
        public System.DateTime Add_Date { get; set; }
        public System.DateTime Change_date { get; set; }
        public long OwnerID { get; set; }
        public long WherhouseID { get; set; }
        public string Details { get; set; }
        public string Input_Name { get; set; }
        public string Pic1 { get; set; }
        public string Pic2 { get; set; }
        public string Pic3 { get; set; }
        public string Pic4 { get; set; }
        public string Pic5 { get; set; }
    
        public virtual User Owner { get; set; }
        public virtual Type Type { get; set; }
        public virtual User Wherhouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptDetail> ReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowDetail> RowDetailsD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RowDetail> RowDetailsS { get; set; }
    }
}
