//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anbarii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentId { get; set; }
        public string ReferenceNumber { get; set; }
        public string StatusPayment { get; set; }
        public int CardID { get; set; }
        public long SaleReferenceId { get; set; }
        public System.DateTime Date { get; set; }
        public string Token { get; set; }
        public int StatePortal { get; set; }
        public long OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Card Card { get; set; }
    }
}
